module.exports = {
    tutorials: [{type: 'autogenerated', dirName: 'tutorials'}],
    contributing: [{type: 'autogenerated', dirName: 'contributing'}],
    lab: [{type: 'autogenerated', dirName: 'lab'}],
}