module.exports = {
    artworks: [{type: 'autogenerated', dirName: 'artworks'}],
    portfolio: [{type: 'autogenerated', dirName: 'portfolio'}],
    miscellaneous: [{type: 'autogenerated', dirName: 'miscellaneous'}],
}