module.exports = {
    artworks: [{type: 'autogenerated', dirName: 'artworks'}],
    projects: [{type: 'autogenerated', dirName: 'projects'}],
    miscellaneous: [{type: 'autogenerated', dirName: 'miscellaneous'}],
}